### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by mrcnski** [NinjaTrappeur/my-repo-pins#7]
Hi Ninja,

Love the project! It's really useful and saves me a lot of time - but there's a delay of a few seconds whenever I run the command. It'd be awesome if there was a way to avoid the delay. I feel like I don't have *that* many repos cloned - maybe 100 at most. I'm on OSX with Emacs 28.

**Comment by picnoir** [comment]
Heya,

> but there's a delay of a few seconds whenever I run the command. 

Oof, that's bad :) It's pretty much instant of my setup (linux desktop + emacs 28).

As it is, the plugin recursively walks the code-root tree until it finds a git repo. There's no caching involved. That could potentially be the issue here. Be it because of slower hardware and/or slower filesystem access on macos or because you have a deeply nested folder that is not a git tree.

In any case, there are solutions and we should fix this! First, let's see what the issue really is here.

Could you run the following snippet on your machine:

```elisp
(defun profile-my-repo-pins ()
  (profiler-start 'cpu+mem)
  (my-repo-pins--get-code-root-projects (my-repo-pins--safe-get-code-root))
  (profiler-stop)
  (profiler-report))

(profile-my-repo-pins)
```

and paste the result here. 

For instance, I get:

```txt
      3,724,479 100% - command-execute
      3,724,479 100%  - call-interactively
      3,724,479 100%   - funcall-interactively
      3,724,479 100%    - eval-last-sexp
      3,724,479 100%     - elisp--eval-last-sexp
      3,724,479 100%      - eval
      3,724,479 100%       - progn
      3,724,479 100%        - profile-my-repo-pins
      3,526,880  94%           profiler-stop
        196,968   5%         - my-repo-pins--get-code-root-projects
        172,216   4%          - my-repo-pins--find-git-dirs-recursively
        157,744   4%           - my-repo-pins--find-git-dirs-recursively
         76,352   2%            - my-repo-pins--find-git-dirs-recursively
          8,184   0%               my-repo-pins--find-git-dirs-recursively
         24,752   0%            mapcar
            631   0%           profiler-start
              0   0%   ...
```

And, just to be sure that the tree walker is the actual issue, could you give me the result of:

```elisp
(defun my-repo-pins-timing ()
  (setq init-time (float-time))
  (my-repo-pins--get-code-root-projects (my-repo-pins--safe-get-code-root))
  (setq done-time (float-time))
  (message "Code tree walked in: %f" (- done-time init-time)))

(my-repo-pins-timing)
```

It should appear in your `*Messages*` buffer. For instance, I get:

```
Code tree walked in: 0.015151
```

**Comment by mrcnski** [comment]
Thanks for the quick response! Here's what I got:

```
        1461 100% - command-execute
        1461 100%  - funcall-interactively
        1461 100%   - eval-defun
        1461 100%    - elisp--eval-defun
        1461 100%     - setq
        1461 100%      - progn
        1461 100%       - profile-my-repo-pins
        1458  99%        - my-repo-pins--get-code-root-projects
        1458  99%         - my-repo-pins--find-git-dirs-recursively
        1457  99%          - my-repo-pins--find-git-dirs-recursively
        1450  99%           - my-repo-pins--find-git-dirs-recursively
        1447  99%            - my-repo-pins--find-git-dirs-recursively
        1360  93%             - my-repo-pins--find-git-dirs-recursively
        1132  77%              - my-repo-pins--find-git-dirs-recursively
         815  55%               - my-repo-pins--find-git-dirs-recursively
         489  33%                - my-repo-pins--find-git-dirs-recursively
         237  16%                 - my-repo-pins--find-git-dirs-recursively
         119   8%                  - my-repo-pins--find-git-dirs-recursively
          63   4%                   - my-repo-pins--find-git-dirs-recursively
          26   1%                    - my-repo-pins--find-git-dirs-recursively
           8   0%                     - my-repo-pins--find-git-dirs-recursively
           2   0%                        my-repo-pins--find-git-dirs-recursively
           1   0%        + profiler-start
           0   0% + ...
```

```
Code tree walked in: 2.691694
```

I tried deleting a very large repo (https://github.com/paritytech/substrate) and it brought the time down in half. Then I deleted a few more (e.g. the rustlang repo) and it didn't seem to have any effect. I'm still playing around with it to see what's up with that one repo.

> you have a deeply nested folder that is not a git tree.

Not sure I understand how `my-repo-pins` works and I haven't read the source - but is there a reason to recurse beyond the `<domain>/<user>/<repo>` level? I would just code it with the assumption that anything within that directory structure is a git repo.

**Comment by mrcnski** [comment]
I deleted my whole `github.com` folder and it went down to `.3` seconds. Then I added that repo back and it didn't affect the time at all. 🤔

**Comment by mrcnski** [comment]
Deleting my [worktrees](https://git-scm.com/docs/git-worktree) consistently makes a huge difference. I'm guessing that's the cause - your code is probably not able to identify those as git repos.

**Comment by picnoir** [comment]
Ok. Great! At least we know the tree walker is the culprit here.

I think the issue here is that we're walking too deep and start walking in a project repository.

> Not sure I understand how my-repo-pins works and I haven't read the source - 

As it is, it's terribly dumb. It's walking the tree until it finds a `.git` directory https://github.com/NinjaTrappeur/h.el/blob/6ba60541656d6f0088fddab6753ddbde7a5f911c/my-repo-pins.el#L454

This assumption obviously won't hold if you have any non-git repositories (svn/mercury/tarball). That being said, I mostly wrote this software for myself, it worked, I ruled it good enough :)

Let's fix that.

>  but is there a reason to recurse beyond the <domain>/<user>/<repo> level?

Yeah, I personally need a escape hatch for some weird repos not following this naming convention (AKA. OpenBSD in my case).

> I would just code it with the assumption that anything within that directory structure is a git repo.

That's a solution indeed. We could expose a customizable variable allowing the user to specify a level after which the plugin won't recurse further.

I'm also thinking about setting up some heuristics. IE. if there's more than X sources files in a directory, then it's probably a project, and we shouldn't recurse further.

So, we have 2 options:

1. Set a max depth variable to stop the tree walker from doing something stupid.
2. Use some heuristics to detect when the tree walker does something stupid.

What do you think? Do you have a preference here?

**Comment by picnoir** [comment]
> Deleting my [worktrees](https://git-scm.com/docs/git-worktree) consistently makes a huge difference. I'm guessing that's the cause - your code is probably not able to identify those as git repos.

Aha, good catch!

--------------------------------------------

Hey, don't butcher your repo to make it fit this buggy software! It should definitely be the other way around :smile:

**Comment by mrcnski** [comment]
> So, we have 2 options:

>    Set a max depth variable to stop the tree walker from doing something stupid.
>    Use some heuristics to detect when the tree walker does something stupid.

Yeah, I personally would, just in case someone has a weird folder in their structure for some reason - at least printing out a warning message would be helpful. But as for me, it seems my problem is now known:

```
Code tree walked in: 0.007359
```

After removing all my worktrees and nothing else. :)

**Comment by picnoir** [comment]
I think I agree with you, it's more robust. I'm going to let this rest until tonight just to be sure.

WRT. message. Good idea!

I'll implement this and push a fix tonight. Thanks for the bug report and the interactive debugging session :)

**Comment by mrcnski** [comment]
Cool! Thanks so much for the help! I use worktrees a lot, so a fix would be super appreciated. Let me know if I can help at all.

**Comment by picnoir** [comment]
> Let me know if I can help at all.

Yup, you can! Could you confirm https://github.com/NinjaTrappeur/my-repo-pins/pull/8 fix the issue?

**Comment by mrcnski** [comment]
> > Let me know if I can help at all.
> 
> Yup, you can! Could you confirm #8 fix the issue?

Thanks! It fixes the delay, but I can't open worktrees. Would be nice if I could! It should be enough to check for the existence of a `.git` file (as opposed to the `.git` folder) and follow the link to the repo inside the file:

```
gitdir: /Users/marcin/Sync/Repos/github.com/SkynetLabs/skynet-js/.git/worktrees/skynet-js-2
```

Or maybe it can just accept any folder inside the tree as a valid project. 🙂

**Comment by picnoir** [comment]
Okay, let's open another issue for that, I won't address it today.
